version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/template # 배포될 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh # ApplicationStart 단계에서 deploy.sh 실행
      timeout: 60
      runas: ec2-user
