server:
  port: ${PORT:8080}
  data:
    redis:
      lettuce:
        pool:
          max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
          max-idle: 5 # pool의 'idle' 커넥션 최대수
          min-idle: 2
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    demo:
      webflux: DEBUG