version: "3"
services:
  redis-docker:
    image: redis:latest
    command: redis-server --requirepass template123 --port 6379
    container_name: "docker-redis"
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379