version: "3"
services:
  mariadb-docker:
    image: docker.io/bitnami/mariadb:10.6
    container_name: "docker-mariadb"
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: template
      MARIADB_USER: user
      MARIADB_PASSWORD: user123
    labels:
      - "name=mariadb"
      - "mode=standalone"
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always

  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    restart: always
